import type { Metadata } from 'next'
import { Inter, Open_Sans } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const open_sans = Open_Sans({ subsets: ['latin'], variable: "--open-sans" })

export const metadata: Metadata = {
  title: 'Prueba Técnica',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${open_sans.className} ${open_sans.variable}`}>{children}</body>
    </html>
  )
}
